
import React from 'react';
import type { ReportData } from '../types';

interface PdfReportProps {
  reportData: ReportData;
}

export const PdfReport: React.FC<PdfReportProps> = ({ reportData }) => {
  return (
    <div style={{ width: '8.27in', padding: '0.5in', backgroundColor: 'white', color: 'black', fontFamily: 'sans-serif', boxSizing: 'border-box', minHeight: '11.69in', display: 'flex', flexDirection: 'column' }}>
      <div style={{ borderBottom: '2px solid #333', paddingBottom: '10px', marginBottom: '20px', textAlign: 'center' }}>
        <h1 style={{ fontSize: '24px', fontWeight: 'bold', margin: 0 }}>AI X-Ray Medical Report</h1>
      </div>

      <div style={{ marginBottom: '20px' }}>
        <h2 style={{ fontSize: '18px', fontWeight: 'bold', borderBottom: '1px solid #ccc', paddingBottom: '5px', marginBottom: '10px' }}>Image Analysis</h2>
        <div style={{ display: 'flex', justifyContent: 'space-around', gap: '20px' }}>
          <div style={{ textAlign: 'center', width: '45%' }}>
            <h3 style={{ fontSize: '14px', fontWeight: 'bold' }}>Original Image</h3>
            <img src={reportData.originalImage} alt="Original X-ray" style={{ maxWidth: '100%', border: '1px solid #ddd', borderRadius: '4px' }} />
          </div>
          <div style={{ textAlign: 'center', width: '45%' }}>
            <h3 style={{ fontSize: '14px', fontWeight: 'bold' }}>Analyzed Image</h3>
            <img src={reportData.analyzedImage} alt="Analyzed X-ray" style={{ maxWidth: '100%', border: '1px solid #ddd', borderRadius: '4px' }} />
          </div>
        </div>
      </div>

      <div style={{ marginBottom: '20px', flexGrow: 1 }}>
        <h2 style={{ fontSize: '18px', fontWeight: 'bold', borderBottom: '1px solid #ccc', paddingBottom: '5px', marginBottom: '10px' }}>Generated Findings</h2>
        <p style={{ fontSize: '12px', whiteSpace: 'pre-wrap', lineHeight: '1.6' }}>
          {reportData.reportText}
        </p>
      </div>

      <div style={{ borderTop: '1px solid #ccc', paddingTop: '10px', fontSize: '10px', color: '#555', marginTop: 'auto' }}>
        <p><strong>Model Used:</strong> {reportData.modelName}</p>
        <p><strong>Report Generated:</strong> {reportData.timestamp}</p>
        <p style={{ marginTop: '10px', fontStyle: 'italic' }}>
          Disclaimer: This report is generated by an AI model and is for informational purposes only. It should not be used as a substitute for professional medical advice, diagnosis, or treatment.
        </p>
      </div>
    </div>
  );
};
